---
title: "Compiler Error CS0103 | Microsoft Docs"
ms.custom: ""
ms.date: "11/17/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "error-reference"
f1_keywords: 
  - "CS0103"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS0103"
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
caps.handback.revision: 13
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Compiler Error CS0103
Le nom 'identificateur' n'existe pas dans le contexte actuel  
  
 Une tentative a été faite pour utiliser un nom qui n'existe pas dans la classe, dans [espace de noms](../../../csharp/language-reference/keywords/namespace.md) ou dans la portée.  Vérifiez l'orthographe du nom et vérifiez vos instructions using et références d'assembly afin de vous assurer que le nom que vous essayer d'utiliser est disponible.  
  
 Cette erreur se produit souvent si vous déclarez une variable dans une boucle ou un bloc `try` ou `if`, puis tentez d'y accéder à partir d'un bloc de code englobant ou d'un autre bloc de code, comme le montre l'exemple suivant.  
  
```c#  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```  
  
 L'exemple suivant résout l'erreur.  
  
```c#  
  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```